Currently Loaded Modulefiles:
 1) cuda/11.0   2) anaconda3/2022.05  
Traceback (most recent call last):
  File "/home/nlabiosa/llama/generate_rationales.py", line 2, in <module>
    from transformers import LlamaTokenizer, LlamaForQuestionAnswering
ImportError: cannot import name 'LlamaForQuestionAnswering' from 'transformers' (/home/nlabiosa/.conda/envs/llava/lib/python3.10/site-packages/transformers/__init__.py)
